language: python
python:
  - "3.7"
# command to install dependencies
install:
  - export PIPENV_PIPFILE="app/helloworld/Pipfile"
  - pip install pipenv
  - pipenv install --system --deploy
# command to run tests
script:
  - make test